#!/bin/sh

set -e

if [ "$1" = "configure" ]; then

        # Create the "spikor-forge" user
        if ! getent passwd spikor-forge > /dev/null; then
                adduser --quiet --system --group --home /var/lib/spikor-forge  \
                        --no-create-home                                 \
                        --gecos "Spikor Forge daemon" \
                        spikor-forge
        fi

        # Set correct permissions and ownership for the application
        if ! dpkg-statoverride --list /usr/share/spikor-forge/config.ru >/dev/null 2>&1; then
                dpkg-statoverride --update --add spikor-forge spikor-forge 0644 /usr/share/spikor-forge/config.ru
        fi

        if ! dpkg-statoverride --list /var/lib/spikor-forge >/dev/null 2>&1; then
                dpkg-statoverride --update --add spikor-forge spikor-forge 0750 /var/lib/spikor-forge
        fi

        if ! dpkg-statoverride --list /var/lib/spikor-forge/modules >/dev/null 2>&1; then
                dpkg-statoverride --update --add spikor-forge spikor-forge 0750 /var/lib/spikor-forge/modules
        fi

fi

#DEBHELPER#
